import 'package:flutter/material.dart';

class AIResumeBuilderScreen extends StatefulWidget {
  const AIResumeBuilderScreen({super.key});

  @override
  State<AIResumeBuilderScreen> createState() => _AIResumeBuilderScreenState();
}

class _AIResumeBuilderScreenState extends State<AIResumeBuilderScreen> {
  final name = TextEditingController();
  final skills = TextEditingController();
  final education = TextEditingController();

  bool generated = false;

  void generate() {
    setState(() {
      generated = true;
    });
  }

  Widget skillChip(String skill) {
    return Container(
      margin: const EdgeInsets.only(right: 8, bottom: 8),
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
      decoration: BoxDecoration(
        color: Colors.indigo.shade50,
        borderRadius: BorderRadius.circular(20),
      ),
      child: Text(skill),
    );
  }

  Widget resumeDesign() {
    List<String> skillList = skills.text.split(",");

    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(25),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(blurRadius: 12, color: Colors.black.withOpacity(0.08)),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          /// HEADER
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Colors.indigo,
              borderRadius: BorderRadius.circular(12),
            ),
            child: Row(
              children: [
                const CircleAvatar(
                  radius: 30,
                  backgroundColor: Colors.white,
                  child: Icon(Icons.person, color: Colors.indigo, size: 32),
                ),

                const SizedBox(width: 16),

                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      name.text,
                      style: const TextStyle(
                        color: Colors.white,
                        fontSize: 22,
                        fontWeight: FontWeight.bold,
                      ),
                    ),

                    const Text(
                      "Professional Candidate",
                      style: TextStyle(color: Colors.white70),
                    ),
                  ],
                ),
              ],
            ),
          ),

          const SizedBox(height: 25),

          /// EDUCATION
          const Text(
            "Education",
            style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
          ),

          const SizedBox(height: 10),

          Container(
            padding: const EdgeInsets.all(14),
            decoration: BoxDecoration(
              color: const Color(0xfff4f6fb),
              borderRadius: BorderRadius.circular(10),
            ),
            child: Text(education.text),
          ),

          const SizedBox(height: 20),

          /// SKILLS
          const Text(
            "Skills",
            style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
          ),

          const SizedBox(height: 10),

          Wrap(children: skillList.map((e) => skillChip(e.trim())).toList()),

          const SizedBox(height: 25),

          /// FOOTER
          Center(
            child: Text(
              "Generated by Credential Graph AI Resume",
              style: TextStyle(color: Colors.grey.shade600, fontSize: 12),
            ),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("AI Resume Builder")),

      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),

        child: Column(
          children: [
            /// INPUT CARD
            Container(
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                color: const Color(0xfff4f6fb),
                borderRadius: BorderRadius.circular(14),
              ),
              child: Column(
                children: [
                  TextField(
                    controller: name,
                    decoration: const InputDecoration(labelText: "Name"),
                  ),

                  TextField(
                    controller: education,
                    decoration: const InputDecoration(labelText: "Education"),
                  ),

                  TextField(
                    controller: skills,
                    decoration: const InputDecoration(
                      labelText: "Skills (comma separated)",
                    ),
                  ),

                  const SizedBox(height: 20),

                  SizedBox(
                    width: double.infinity,
                    child: ElevatedButton(
                      onPressed: generate,
                      child: const Text("Generate Resume"),
                    ),
                  ),
                ],
              ),
            ),

            const SizedBox(height: 30),

            if (generated) resumeDesign(),
          ],
        ),
      ),
    );
  }
}
