// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATtshHn-ut1xJ1VXV-meJ7Yt3nXl3LcJg',
    appId: '1:1089960799328:web:fb93f0776b06bcc071e705',
    messagingSenderId: '1089960799328',
    projectId: 'credential-graph',
    authDomain: 'credential-graph.firebaseapp.com',
    storageBucket: 'credential-graph.firebasestorage.app',
    measurementId: 'G-DKDPYEJX9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA32qlVsrrO9leAdE4zW8OPT8fcFntaGl0',
    appId: '1:1089960799328:android:5ffe1be88db2c3c571e705',
    messagingSenderId: '1089960799328',
    projectId: 'credential-graph',
    storageBucket: 'credential-graph.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlzZcYGOwh4EkiIj4eJFMIpuMc5SrtzOw',
    appId: '1:1089960799328:ios:6b87f0067ea3437f71e705',
    messagingSenderId: '1089960799328',
    projectId: 'credential-graph',
    storageBucket: 'credential-graph.firebasestorage.app',
    iosBundleId: 'com.example.credentialGraph',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlzZcYGOwh4EkiIj4eJFMIpuMc5SrtzOw',
    appId: '1:1089960799328:ios:6b87f0067ea3437f71e705',
    messagingSenderId: '1089960799328',
    projectId: 'credential-graph',
    storageBucket: 'credential-graph.firebasestorage.app',
    iosBundleId: 'com.example.credentialGraph',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATtshHn-ut1xJ1VXV-meJ7Yt3nXl3LcJg',
    appId: '1:1089960799328:web:b756c7ced79896c671e705',
    messagingSenderId: '1089960799328',
    projectId: 'credential-graph',
    authDomain: 'credential-graph.firebaseapp.com',
    storageBucket: 'credential-graph.firebasestorage.app',
    measurementId: 'G-LCG6W1681F',
  );
}
